# Python in Data Science

The programming requirements of data science demands a very versatile yet flexible language which is simple to write the code but can handle highly complex mathematical processing. Python is most suited for such requirements as it has already established itself both as a language for general computing as well as scientific computing. More over it is being continuously upgraded in form of new addition to its plethora of libraries aimed at different programming requirements. Below we will discuss such features of python which makes it the preferred language for data science.

 + A simple and easy to learn language which achieves result in fewer lines of code than other similar languages like R. Its simplicity also makes it robust to handle complex scenarios with minimal code and much less confusion on the general flow of the program.
 + It is cross platform, so the same code works in multiple environments without needing any change. That makes it perfect to be used in a multi-environment setup easily.
 + It executes faster than other similar languages used for data analysis like R and MATLAB.
 + Its excellent memory management capability, especially garbage collection makes it versatile in gracefully managing very large volume of data transformation, slicing, dicing and visualization.
 + Most importantly Python has got a very large collection of libraries which serve as special purpose analysis tools. For example – the NumPy package deals with scientific computing and its array needs much less memory than the conventional python list for managing numeric data. And the number of such packages is continuously growing.
 + Python has packages which can directly use the code from other languages like Java or C. This helps in optimizing the code performance by using existing code of other languages, whenever it gives a better result.

Our aim is here to learn some basics of Python before going into complex coding for data science and statistics. Let's look at some basic concept in python.

# Python Basic

This tutorial start off with the basic concept that we must learn before starting any Data Science projects. These concepts are:

 1. Variables , data types and operators
 2. Data Structures
 3. Control Flow Statements
 4. Functions
 5. Python Syntax essentials

## 1. Variables , data types and operators

### 1.1 Variables

Variables is a name that is used to denote something or a value is called a variable. In python, variables can be declared and values can be assigned to it as follows,

In [ ]:
x = 2
y = 5
z = "Hey"

From now on, if we type these variables, the assigned values will be returned:

In [ ]:
z

'Hey'

In [ ]:
x

2

### 1.2 Data types

Just like other programming language, Python has different data types. Below are most common used data types:

 + Boolean
 + String
 + Integer
 + Float

Let's look at example of one of these:

In [ ]:
is_vaccinated = True
dog_name = "Brutus"
age = 10
height = 1.2

For instance the *dog_name* variable holds a **string**: (Brutus). In Python 3 a string is a sequence of Unicode characters (eg. numbers, letters, punctuation, etc.), so it can have numbers or exclamation marks or almost anything (eg. ‘R2-D2’ is a valid string). In Python it’s super easy to identify a string as it’s usually between quotation marks. The *age* variables store **integers** (10), which is a numeric Python data type. Another numeric data type is **float**, in our example: height, which is 1.2.
The *is_vaccinated*’s True value is a so called **boolean** value. Booleans can be only True or False.

Below is the quick summary:

| Var        | Value           | Type  |
| ------------ |:------------------ : | -------:|
| is_vaccinated    | True | boolean |
| dog_name      | "Brutus"     |   string |
| age | 10      |    integer |
| height | 1.2      |   float |

### 1.3. Operators

Like other programming language, there are various operators used in python as well which are:

 + Arithmetic Operators
 + Relational Operators
 + Logical  Operators
 
Let's look at these operators one by one.

#### 1.3.1. Arithmetic Operators

Arithmetic operators are used to perform mathematical operations like addition, subtraction, multiplication and division.

| Operator        | Task          | Syntax |
| ------------ |:------------------ : |:------------------ : |
| +    | Addition: adds two operands| x + y
| -     | Subtraction: subtracts two operands|  x - y
| /    | Division (float): divides the first operand by the second     |   x / y
| %  | Modulus: returns the remainder when first operand is divided by the second     |  x % y
| *  | Multiplication: multiplies two operands     |  x * y
| //  | Division (floor): divides the first operand by the second      |  x // y
| **  | Exponeation : Raise to the power of given number     |  x**2

Let's look at examples of above operators.

#### 1.3.2 Relational Operators

Relational operators compares the values. It either returns True or False according to the condition.

| Operator        | Task          | Syntax |
| ------------ |:------------------ : |:------------------ : |
| >    | Greater than| x > y
| <     | Less than|  x < y
| ==    | True, if it is equal  |   x == y
| !=  | True, if not equal to    |  x != y
| >=  | Greater than or equal to   |  x >= y
| <=  | less than or equal to |  x <= y

Let's look at examples of above operators.

In [ ]:
# Examples of Arithmetic Operator 
a = 9
b = 4
  
# Addition of numbers 
add = a + b 
# Subtraction of numbers  
sub = a - b 
# Multiplication of number  
mul = a * b 
# Division(float) of number  
div1 = a / b 
# Division(floor) of number  
div2 = a // b 
# Modulo of both number 
mod = a % b 
# Exponeation
exp = a**2

# print results 
print(add) 
print(sub) 
print(mul) 
print(div1) 
print(div2) 
print(mod) 
print(exp)

13
5
36
2.25
2
1
81

In [ ]:
# Examples of Relational Operators 
a = 13
b = 33
  
# a > b is False 
print(a > b) 
  
# a < b is True 
print(a < b) 
  
# a == b is False 
print(a == b) 
  
# a != b is True 
print(a != b) 
  
# a >= b is False 
print(a >= b) 
  
# a <= b is True 
print(a <= b)

False
True
False
True
False
True

#### 1.3.3 Logical operators

Logical operators perform Logical AND, Logical OR and Logical NOT operations.

| Operator        | Task          | Syntax |
| ------------ |:------------------ : |:------------------ : |
| and    | and: perform and condition| x and y |
| or     | or: perform or condition|  x or y |
| not    | not: perform not condition     |   not x|

In [ ]:
# Examples of Logical Operator 
a = True
b = False
  
# Print a and b is False 
print(a and b) 
  
# Print a or b is True 
print(a or b) 
  
# Print not a is False 
print(not a)

False
True
False

## 2. Data Structures

Sometimes in Python we need to store relevant information together in one object – instead of several small variables. This is where Data Structures comes very handy.

Below are major Python data structures:

 + Lists
 + Tuples
 + Sets
 + Dictionaries
 
All above are good for different things and we have to use them slightly differently. Let’s understand each one by one.

### 2.1 Lists

A list is a sequence of values. Basically, it’s data put into brackets and separated by commas. An easy example – a list of integers:

>[3, 4, 1, 4, 5, 2, 7]

It’s important to know that in Python, a list is an object – and generally speaking it’s treated like any other data type (e.g. integers, strings, booleans, etc.). This means that we can assign our list to a variable, so we can store and make it easier to access:

In [ ]:
my_first_list = [3, 4, 1, 4, 5, 2, 7]
my_first_list

[3, 4, 1, 4, 5, 2, 7]

A list can hold every other type of data, not just integers – strings, Booleans, even other lists. Let's call example from first topic in which we have stores different values of dog in different variables.

In [ ]:
is_vaccinated = True
dog_name = "Brutus"
age = 10
height = 1.2

With help of lists, We can store these attributes in one list instead of 4 different variables.

In [ ]:
dog = ['Brutus', 10, True, 1.2]
dog

['Brutus', 10, True, 1.2]

Now let’s say that Brutus has two belongings: a bone and a little ball. We can store those belongings as a list inside our first list simply called nested list.

In [ ]:
dog = ['Brutus', 10, True, 1.2, ['bone', 'little ball']]
dog

['Brutus', 10, True, 1.2, ['bone', 'little ball']]

> **Important thing to remember is that we can store lists in lists.**

In [ ]:
sample_matrix = [[1, 4, 9], [1, 8, 27], [1, 16, 81]]
sample_matrix

[[1, 4, 9], [1, 8, 27], [1, 16, 81]]

**Indexing:**

**How to access a specific element of a Python list?**

Now that we have stored these values, it’s really essential to know how to access them in the future. As we have already seen, we can get the whole Python list returned if we type the right variable name. For ex:

In [ ]:
dog

['Brutus', 10, True, 1.2, ['bone', 'little ball']]

But how do we call one particular item from our list? Firstly, think a bit about how we can refer to a value in theory… The only thing that comes into play is the position of the value. E.g. if we want to call the first element on the dog list, we have to type the name of the list and the number of the element between brackets, like this: [1]. Let's try this:dog[1]

In [ ]:
dog[1]

10

**10** was the second element on the list, not the first. Here, we have to remeber very important concept about Python indexing:

> **Python uses so-called “zero-based indexing”, which means that the first element’s number is [0], the second is [1], the third is [2] and so on.**

Let's try to print all the list elements one by one:

In [ ]:
dog[0]

'Brutus'

In [ ]:
dog[1]

10

In [ ]:
dog[2]

True

In [ ]:
dog[3]

1.2

In [ ]:
dog[4]

['bone', 'little ball']

**How to access a specific element of a nested Python list**

Can we find out how to get the ‘bone’ element, which is located in a nested list? Actually it’s super-intuitive.

It’s gonna be the zeroth element of our fourth element! The syntax is:
dog[4][0]

In [ ]:
dog[4][1]

'little ball'

Indexing can also be done in reverse order. That is the last element can be accessed first. Here, indexing starts from -1.

In [ ]:
dog[-1]

['bone', 'little ball']

**Slicing:**

Indexing was only limited to accessing a single element, Slicing on the other hand is accessing a sequence of data inside the list. In other words "slicing" the list.

Slicing is done by defining the index values of the first element and the last element from the parent list that is required in the sliced list. It is written as parentlist[ a : b ] where a,b are the index values from the parent list. If a or b is not defined then the index value is considered to be the first value for a if a is not defined and the last value for b when b is not defined.

In [ ]:
num = [10,11,12,13,14,15,16,17,18,19]
print (num[0:4])
print (num[4:])

[10, 11, 12, 13]
[14, 15, 16, 17, 18, 19]

**Built in Functions:**

There are some built in list functions. Most commons are:

 + len
 + min
 + max
 + count
 + append
 + index
 + insert
 + remove
 + del
 + reverse
 + sort
 + list
 
 
 **1. len()**
 
 To find the length of the list or the number of elements in a list, **len( )** is used.

In [ ]:
num = [0,1,2,3,4,5,6,7,8,9]
len(num)

10

**2. min( ) and max()**

If the list consists of all integer elements then **min( )** and **max( )** gives the minimum and maximum value in the list.

In [ ]:
print(min(num))
print(max(num))

0
9

In a list with elements as string, **max( )** and **min( )** is applicable. **max( )** would return a string element whose ASCII value is the highest and the lowest when **min( )** is used. Note that only the first index of each element is considered each time and if they value is the same then second index considered so on and so forth.

In [ ]:
mlist = ['bzaa','ds','nc','az','z','klm']
print (max(mlist))
print (min(mlist))

z
az

Here the first index of each element is considered and thus *z* has the highest ASCII value thus it is returned and minimum ASCII is *a*. But what if numbers are declared as strings?

In [ ]:
nlist = ['1','94','93','1000']
print (max(nlist))
print (min(nlist))

94
1

Even if the numbers are declared in a string the first index of each element is considered and the maximum and minimum values are returned accordingly. Hence, **max()** returns *9* as its ASCII value is high and **min()** returns *1* as its ASCII value is low.

But if we want to find the **max( )** string element based on the length of the string then another parameter '**key=len**' is declared inside the **max( )** and **min( )** function.

In [ ]:
names = ['Earth','Air','Fire','Water']
print (max(names, key=len))
print (min(names, key=len))

Earth
Air

Here, min looks ok but why *Earth* is flagged as max when *Water* is also present with same lenght. Here we have to note that **max()** or **min()** function returns the first element when there are two or more elements with the same length.

**3. count( )**

**count( )** is used to count the number of a particular element that is present in the list.

In [ ]:
lst = [1,1,4,4,4,48,7]
lst.count(4)

3

**4. append( ) and extend()**

**append( )** function can also be used to add a entire list at the end. Observe that the resultant list becomes a nested list. But if nested list is not what is desired then **extend( )** function can be used.

In [ ]:
lst1 = [5,4,2,8]
lst.append(lst1)
print (lst)

[1, 1, 4, 4, 4, 48, 7, [5, 4, 2, 8]]

In [ ]:
lst = [1,1,4,8,7]
lst.extend(lst1)
print (lst)

[1, 1, 4, 8, 7, 5, 4, 2, 8]

**5. index( )**

**index( )** is used to find the index value of a particular element. Note that if there are multiple elements of the same value then the first index value of that element is returned.

In [ ]:
lst.index(1)

0

**6. insert( )**

**insert(x,y)** is used to insert a element y at a specified index value x. **append( )** function made it only possible to insert at the end.

In [ ]:
lst = [1,1,4,8,7,6,8]
lst

[1, 1, 4, 8, 7, 6, 8]

In [ ]:
lst.insert(5, 'name')
print (lst)

[1, 1, 4, 8, 7, 'name', 6, 8]

**insert(x,y)** inserts but does not replace element. If you want to replace the element with another element you simply assign the value to that particular index.

In [ ]:
lst[5] = 'Python'
print (lst)

[1, 1, 4, 8, 7, 'Python', 6, 8]

**7. remove( ) and del**

One can remove element by specifying the element itself using the **remove( )** function. Alternative to remove function but with using index value is **del**.

In [ ]:
lst.remove('Python')
print (lst)

del lst[1]
print (lst)

[1, 1, 4, 8, 7, 6, 8]
[1, 4, 8, 7, 6, 8]

**8. reverse( )**

The entire elements present in the list can be reversed by using the reverse() function. Note that the nested list [5,4,2,8] is treated as a single element of the parent list lst. Thus the elements inside the nested list is not reversed.

In [ ]:
print (lst)
lst.reverse()
print (lst)

lst1 = [5,4,2,8]
lst.append(lst1)
print (lst)
lst.reverse()
print (lst)

[1, 4, 8, 7, 6, 8]
[8, 6, 7, 8, 4, 1]
[8, 6, 7, 8, 4, 1, [5, 4, 2, 8]]
[[5, 4, 2, 8], 1, 4, 8, 7, 6, 8]

**9. sort( )**

Python offers built in operation **sort( )** to arrange the elements in ascending order. For descending order, By default the reverse condition will be False for reverse. Hence changing it to True would arrange the elements in descending order. Similarly for lists containing string elements, **sort( )** would sort the elements based on it's ASCII value in ascending and by specifying **reverse=True** in descending. To sort based on length key=len should be specified as shown.

In [ ]:
# Sorting numeric list
lst = [1,1,4,8,7]
lst.sort()
print (lst)
lst.sort(reverse=True)
print (lst)

# Sorting string list
names = ['Earth','Air','Fire','Water']
names.sort()
print (names)
names.sort(reverse=True)
print (names)

# Sorting string list by length
names.sort(key=len)
print (names)
names.sort(key=len,reverse=True)
print (names)

[1, 1, 4, 7, 8]
[8, 7, 4, 1, 1]
['Air', 'Earth', 'Fire', 'Water']
['Water', 'Fire', 'Earth', 'Air']
['Air', 'Fire', 'Water', 'Earth']
['Water', 'Earth', 'Fire', 'Air']

**10. list( )**

A string can be converted into a list by using the **list()** function.

In [ ]:
list('hello')

['h', 'e', 'l', 'l', 'o']

**Copying a list**

Here, Most of us commit mistake. Consider the following,

In [ ]:
lista= [2,1,4,3]
listb = lista
print (listb)

[2, 1, 4, 3]

Here, We have declared a list, lista = [2,1,4,3]. This list is copied to listb by assigning it's value and it get's copied as seen. Now we perform some random operations on lista.

In [ ]:
lista.remove(3)
print (lista)
lista.append(9)
print (lista)
print (listb)

[2, 1, 4]
[2, 1, 4, 9]
[2, 1, 4, 9]

listb has also changed though no operation has been performed on it. This is because you have assigned the same memory space of lista to listb. So how do fix this?

If you recall, in slicing we had seen that parentlist[a:b] returns a list from parent list with start index a and end index b and if a and b is not mentioned then by default it considers the first and last element. We use the same concept here. By doing so, we are assigning the data of lista to listb as a variable.

In [ ]:
lista = [2,1,4,3]
listb = lista[:]
print (listb)

lista.remove(3)
print (lista)
lista.append(9)
print (lista)
print (listb)

[2, 1, 4, 3]
[2, 1, 4]
[2, 1, 4, 9]
[2, 1, 4, 3]

### 2.2 Tuples

Tuples are similar to lists but only big difference is the elements inside a list can be changed but in tuple it cannot be changed. Think of tuples as something which has to be True for a particular something and cannot be True for no other values.

**How to define it?**

To define a tuple, A variable is assigned to paranthesis ( ) or **tuple( )**. It can also takes a list as input and converts it into a tuple or it takes a string and converts it into a tuple. 

> It follows the same indexing and slicing as Lists.

In [ ]:
tup1 = ('A Game of Thrones', 'Digital Fortress', 'Practical Statistics for Data Scientists')
print(tup1)

tup3 = tuple([1,2,3])
print (tup3)

tup4 = tuple('Hello')
print (tup4)

('A Game of Thrones', 'Digital Fortress', 'Practical Statistics for Data Scientists')
(1, 2, 3)
('H', 'e', 'l', 'l', 'o')

In [ ]:
# Indexing
print(tup3[1])

# slicing
tup5 = tup4[:3]
print(tup5)

2
('H', 'e', 'l')

**Mapping one tuple to another**

In [ ]:
(a,b,c)= ('alpha','beta','gamma')
print(a,b,c)

d = tuple('RajathKumarMP')
print (d)

alpha beta gamma
('R', 'a', 'j', 'a', 't', 'h', 'K', 'u', 'm', 'a', 'r', 'M', 'P')

**Built in functions**

 + count
 + index
 

**count( )** function counts the number of specified element that is present in the tuple whereas **index( )** *italicized text* function returns the index of the specified element. If the elements are more than one then the index of the first element of that specified element is returned

In [ ]:
print(d.count('a'))
print(d.index('a'))

3
1

### 2.3 Sets

Sets are mainly used to eliminate repeated numbers in a sequence/list. It is also used to perform some standard set operations.

Sets are declared as **set( )** which will initialize a empty set. Also **set([sequence])** can be executed to declare a set with elements

In [ ]:
set0 = set([1,2,2,3,3,4])
print (set0)

{1, 2, 3, 4}

Here, elements 2,3 which are repeated twice are seen only once. Thus in a set each element is distinct.

**Built-in Functions**

 + union
 + add
 + intersection
 + difference
 + symmetric_difference
 + issubset, isdisjoint, issuperset
 + remove
 + clear
 
**union( )** function returns a set which contains all the elements of both the sets without repition. 

**add( )** will add a particular element into the set. Note that the index of the newly added element is arbitrary and can be placed anywhere not neccessarily in the end.

**intersection( )** function outputs a set which contains all the elements that are in both sets.

**difference( )** function ouptuts a set which contains elements that are in set1 and not in set2.

**symmetric_difference( )** function ouputs a function which contains elements that are in one of the sets.

**issubset( )**, **isdisjoint( )**, **issuperset( )** is used to check if the set1/set2 is a subset, disjoint or superset of set2/set1 respectively.

**remove( )** function deletes the specified element from the set.

**clear( )** is used to clear all the elements and make that set an empty set.

Let's look at these one by one:

In [ ]:
# Defining two sets
set1 = set([1,2,3])
set2 = set([2,3,4,5])

# union
print(set1.union(set2))

# add
set1.add(0)
print(set1)

# intersection
print(set1.intersection(set2))

# difference
print(set1.difference(set2))

# symmetric_difference
print(set2.symmetric_difference(set1))

# issubset, isdisjoint, issuperset
print(set1.issubset(set2))
print(set2.isdisjoint(set1))
print(set2.issuperset(set1))

# remove
set1.remove(2)
print(set1)

# clear
set1.clear()
print(set1)

{1, 2, 3, 4, 5}
{0, 1, 2, 3}
{2, 3}
{0, 1}
{0, 1, 4, 5}
False
False
False
{0, 1, 3}
set()

### 2.4 Dictionaries

Another useful data type built into Python is the dictionary. Dictionaries are sometimes found in other languages as “associative memories” or “associative arrays”. Unlike sequences, which are indexed by a range of numbers, dictionaries are indexed by keys, which can be any immutable type; strings and numbers can always be keys. Tuples can be used as keys if they contain only strings, numbers, or tuples; if a tuple contains any mutable object either directly or indirectly, it cannot be used as a key. You can’t use lists as keys, since lists can be modified in place using index assignments, slice assignments, or methods like append() and extend().

It is best to think of a dictionary as a set of key: value pairs, with the requirement that the keys are unique (within one dictionary). A pair of braces creates an empty dictionary: { }. Placing a comma-separated list of key:value pairs within the braces adds initial key:value pairs to the dictionary; this is also the way dictionaries are written on output.

The main operations on a dictionary are storing a value with some key and extracting the value given the key. It is also possible to delete a key:value pair with **del**. If you store using a key that is already in use, the old value associated with that key is forgotten. It is an error to extract a value using a non-existent key.

Performing **list(d)** on a dictionary returns a list of all the keys used in the dictionary, in insertion order (if you want it sorted, just use **sorted(d)** instead). To check whether a single key is in the dictionary, use the in keyword.

To define a dictionary, equate a variable to { } or **dict()**.

In [ ]:
d0 = {}
d1 = dict()
print (type(d0), type(d1))

<class 'dict'> <class 'dict'>

In [ ]:
tel = {'jack': 4098, 'sape': 4139}
tel

{'jack': 4098, 'sape': 4139}

In [ ]:
tel = {'jack': 4098, 'sape': 4139}
tel['guido'] = 4127
print(tel)

print(tel['jack'])

del tel['sape']

tel['irv'] = 4127

print(tel)

print(list(tel))

print(sorted(tel))

'guido' in tel

'jack' not in tel

{'jack': 4098, 'sape': 4139, 'guido': 4127}
4098
{'jack': 4098, 'guido': 4127, 'irv': 4127}
['jack', 'guido', 'irv']
['guido', 'irv', 'jack']

False

The **dict( )** constructor builds dictionaries directly from sequences of key-value pairs:

In [ ]:
dict([('sape', 4139), ('guido', 4127), ('jack', 4098)])

{'guido': 4127, 'jack': 4098, 'sape': 4139}

Two lists which are related can be merged to form a dictionary. For this, **zip( )** function is used to combine two lists and then **dict( )** function is used.

In [ ]:
names = ['One', 'Two', 'Three', 'Four', 'Five']
numbers = [1, 2, 3, 4, 5]

a1 = dict(zip(names,numbers))
print (a1)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}

Similar Dictionary can also be built using loops.

In [ ]:
names = ['One', 'Two', 'Three', 'Four', 'Five']
numbers = [1, 2, 3, 4, 5]

for i in range(len(names)):
    a1[names[i]] = numbers[i]
print (a1)

{'One': 1, 'Two': 2, 'Three': 3, 'Four': 4, 'Five': 5}

**Built-in Functions**

**values( )** function returns a list with all the assigned values in the dictionary.

**keys( )** function returns all the index or the keys to which contains the values that it was assigned to.

**items( )** is returns a list containing both the list but each element in the dictionary is inside a tuple. This is same as the result that was obtained when zip function was used.

**clear( )** function is used to erase the entire database that was created.

In [ ]:
# values()
print(a1.values())

#  keys()
print(a1.keys())

# items ()
print(a1.items())

# clear()
a1.clear()
print (a1)

dict_values([1, 2, 3, 4, 5])
dict_keys(['One', 'Two', 'Three', 'Four', 'Five'])
dict_items([('One', 1), ('Two', 2), ('Three', 3), ('Four', 4), ('Five', 5)])
{}

## 3. Control Flow Statements

A program’s control flow is the order in which the program’s code executes. The control flow of a Python program is regulated by **conditional statements**, **loops**, and **function calls**. This section covers the **if** statement , **for** and **while** loops; **functions** are covered in next section.

### 3.1 The if Statement

Often, you need to execute some statements only if some condition holds, or choose statements to execute depending on several mutually exclusive conditions. The Python compound statement if, which uses **if**, **elif**, and **else** clauses, lets you conditionally execute blocks of statements. Here’s the syntax for the if statement:

----
if expression:<br>

    statement(s)
elif expression:<br>

    statement(s)
elif expression:<br>

    statement(s)
...

else:<br>

    statement(s)

----

The **elif** and **else** clauses are optional. Note that unlike some languages, Python does not have a **switch** statement, so you must use **if**, **elif**, and **else** for all conditional processing.

If the expression for the **if** clause evaluates as true, the statements following the **if** clause execute, and the entire **if** statement ends. Otherwise, the expressions for any **elif** clauses are evaluated in order. The statements following the first **elif** clause whose condition is true, if any, are executed, and the entire **if** statement ends. Otherwise, **if** an **else** clause exists, the statements following it are executed.

Here’s some typical **if** statements:

In [ ]:
# if
x = 12
if x > 10:
    print ("Number is greater than 10")

Number is greater than 10

In [ ]:
# else
x = 8
if x > 10:
    print ("Number is greater than 10")
else:
    print ("Number is less than equal to 10")

Number is less than equal to 10

In [ ]:
x = 13
if x < 0:
    print ("x is negative")
elif x % 2:
    print ("x is positive and odd")
else:
    print ("x is even and non-negative")

x is positive and odd

### 3.2 The while Statement

The **while** statement in Python supports repeated execution of a statement or block of statements that is controlled by a conditional expression. Here’s the syntax for the while statement:

----
 while expression:<br>

    statement(s)

----

A while statement can also include an else clause and break and continue statements, as we’ll discuss shortly.

Here’s a typical while statement:

In [ ]:
i = 1
while i < 6:
    print(i ** 2)
    i = i+1
print('End')

1
4
9
16
25
End

First, expression, which is known as the loop condition, is evaluated. If the condition is false, the while statement ends. If the loop condition is satisfied, the statement or statements that comprise the loop body are executed. When the loop body finishes executing, the loop condition is evaluated again, to see if another iteration should be performed. This process continues until the loop condition is false, at which point the while statement ends.

The loop body should contain code that eventually makes the loop condition false, or the loop will never end unless an exception is raised or the loop body executes a break statement. A loop that is in a function’s body also ends if a return statement executes in the loop body, as the whole function ends in this case.

### 3.3 The for Statement

The for statement in Python supports repeated execution of a statement or block of statements that is controlled by an iterable expression. Here’s the syntax for the for statement:

----
for target in iterable:<br>

    statement(s)
----

Note that the **in** keyword is part of the syntax of the **for** statement and is functionally unrelated to the **in** operator used for membership testing. A **for** statement can also include an **else** clause and **break** and **continue** statements, as we’ll discuss shortly.

Here’s a typical for statement:

In [ ]:
for letter in "ciao":
    print ("give me a", letter, "...")

give me a c ...
give me a i ...
give me a a ...
give me a o ...

In [ ]:
for letter in "ciao":
    print(letter)

c
i
a
o

*iterable* may be any Python expression suitable as an argument to built-in function iter, which returns an iterator object (explained in detail in the next section). *target* is normally an identifier that names the control variable of the loop; the **for** statement successively rebinds this variable to each item of the iterator, in order. The statement or statements that comprise the loop body execute once for each item in *iterable* (unless the loop ends because an exception is raised or a *break* or *return* statement is executed).

A target with multiple identifiers is also allowed, as with an unpacking assignment. In this case, the iterator’s items must then be sequences, each with the same length, equal to the number of identifiers in the target. For example, when *a1* is a dictionary, this is a typical way to loop on the items in *a1*:

In [ ]:
for key, value in a1.items( ):
    if not key or not value: del a1[key]    # keep only true keys and values

NameError: ignored

**range and xrange**

Looping over a sequence of integers is a common task, so Python provides built-in functions **range** and **xrange** to generate and return integer sequences. The simplest, most idiomatic way to loop n times in Python is:

----
for i in xrange(n):<br>

    statement(s)
----

range( x ) returns a list whose items are consecutive integers from 0 (included) up to x (excluded). range( x,y ) returns a list whose items are consecutive integers from x (included) up to y (excluded). The result is the empty list if x is greater than or equal to y. range( x,y,step ) returns a list of integers from x (included) up to y (excluded), such that the difference between each two adjacent items in the list is step. If step is less than 0, range counts down from x to y. range returns the empty list when x is greater than or equal to y and step is greater than 0, or when x is less than or equal to y and step is less than 0. If step equals 0, range raises an exception.

While range returns a normal list object, usable for all purposes, xrange returns a special-purpose object, specifically intended to be used in iterations like the for statement shown previously. xrange consumes less memory than range for this specific use. Leaving aside memory consumption, you can use range wherever you could use xrange.

### 3.4 The break Statement

The break statement is allowed only inside a loop body. When break executes, the loop terminates. If a loop is nested inside other loops, break terminates only the innermost nested loop. In practical use, a break statement is usually inside some clause of an if statement in the loop body so that it executes conditionally.

One common use of break is in the implementation of a loop that decides if it should keep looping only in the middle of each loop iteration:

----
while True:                     # this loop can never terminate naturally<br>
    x = get_next( ) <br>
    y = preprocess(x) <br>
    if not keep_looping(x, y): break <br>
    process(x, y) <br>

----

### 3.5 The continue Statement

The continue statement is allowed only inside a loop body. When continue executes, the current iteration of the loop body terminates, and execution continues with the next iteration of the loop. In practical use, a continue statement is usually inside some clause of an if statement in the loop body so that it executes conditionally.

The continue statement can be used in place of deeply nested if statements within a loop. For example:

----
for x in some_container:<br>
    if not seems_ok(x): continue<br>
    lowbound, highbound = bounds_to_test( )<br>
    if x<lowbound or x>=highbound: continue<br>
    if final_check(x):<br>
        do_processing(x)<br>

  ----
  
  This equivalent code does conditional processing without continue:
  
 ----
for x in some_container: <br>
    if seems_ok(x):<br>
        lowbound, highbound = bounds_to_test( )<br>
        if lowbound<=x<highbound:<br>
            if final_check(x):<br>
                do_processing(x)<br>

---

  
Both versions function identically, so which one you use is a matter of personal preference.

### 3.6 The else Clause on Loop Statements
  
Both the while and for statements may optionally have a trailing else clause. The statement or statements after the else execute when the loop terminates naturally (at the end of the for iterator or when the while loop condition becomes false), but not when the loop terminates prematurely (via break, return, or an exception). When a loop contains one or more break statements, you often need to check whether the loop terminates naturally or prematurely. You can use an else clause on the loop for this purpose:

---
for x in some_container:<br>
    if is_ok(x): break             # item x is satisfactory, terminate loop<br>
else:<br>
    print ("Warning: no satisfactory item was found in container")<br>
    x = None<br>
    
---

### 3.7 The pass Statement

The body of a Python compound statement cannot be empty—it must contain at least one statement. The pass statement, which performs no action, can be used as a placeholder when a statement is syntactically required but you have nothing specific to do. Here’s an example of using pass in a conditional statement as a part of somewhat convoluted logic, with mutually exclusive conditions being tested:

---
if condition1(x):<br>
    process1(x)<br>
elif x>23 or condition2(x) and x<5:<br>
    pass                                # nothing to be done in this case<br>
elif condition3(x):<br>
    process3(x)<br>
else:<br>
    process_default(x)<br>
    
---

### 3.8 The try Statement

Python supports exception handling with the try statement, which includes *try*, *except*, *finally*, and *else* clauses. A program can explicitly raise an exception with the *raise* statement.

## 4. Functions

### 4.1 Definition

Most of the times, In a algorithm the statements keep repeating and it will be a tedious job to execute the same statements again and again and will consume a lot of memory and is not efficient. In such cases, Python functions comes very handy.

This is the basic syntax of a function:

---
def funcname(arg1, arg2,... argN):<br>

''' Document String'''<br>

statements<br>


return value
  
---

Read the above syntax as, A function by name "funcname" is defined, which accepts arguements "arg1,arg2,....argN". The function is documented and it is '''Document String'''. The function after executing the statements returns a "value".

In [ ]:
print ("Hey John!")
print ("John, How do you do?")

Hey John!
John, How do you do?

Instead of writing the above two statements every single time it can be replaced by defining a function which would do the job in just one line.

Defining a function firstfunc().

In [ ]:
def firstfunc():
  print ("Hey John!")
  print ("John, How do you do?")
    
firstfunc()

Hey John!
John, How do you do?

**firstfunc()** every time just prints the message to a single person. We can make our function **firstfunc()** to accept arguements which will store the name and then prints respective to that accepted name. To do so, add a argument within the function as shown.

In [ ]:
def firstfunc(username):
    print ("Hey", username ,'!')
    print (username ,',' ,"How do you do?")

In [ ]:
name1 = input('Please enter your name : ')

Please enter your name : Arjun

The name "John" is actually stored in name1. So we pass this variable to the function **firstfunc()** as the variable username because that is the variable that is defined for this function. i.e **name1** is passed as username.

In [ ]:
firstfunc(name1)

Hey Arjun !
Arjun , How do you do?

Let us simplify this even further by defining another function **secondfunc()** which accepts the name and stores it inside a variable and then calls the **firstfunc()** from inside the function itself.

In [ ]:
def firstfunc(username):
    print ("Hey", username + '!')
    print (username + ',' ,"How do you do?")
def secondfunc():
    name = input("Please enter your name : ")
    firstfunc(name)

In [ ]:
secondfunc()

Please enter your name : Arjun
Hey Arjun!
Arjun, How do you do?

### 4.2 Return Statement

When the function results in some value and that value has to be stored in a variable or needs to be sent back or returned for further operation to the main algorithm, return statement is used.The below defined **times( )** function accepts two arguements and return the variable z which contains the result of the product of the two arguements.The z value is stored in variable c and can be used for further operations.

In [ ]:
def times(x,y):
  z = x*y
  return z

In [ ]:
times(4,5)
#print (c)

20

Instead of declaring another variable the entire statement itself can be used in the return statement as shown.

In [ ]:
def times(x,y):
    '''This multiplies the two input arguments'''
    return x*y
  
c = times(4,5)
print (c)

20

Since the **times( )** is now defined, we can document it as shown above. This document is returned whenever **times( )** function is called under **help( )** function.

In [ ]:
help(times)

Help on function times in module __main__:

times(x, y)
    This multiplies the two input arguments

Multiple variable can also be returned, But keep in mind the order.If the function is just called without any variable for it to be assigned to, the result is returned inside a tuple. But if the variables are mentioned then the result is assigned to the variable in a particular order which is declared in the return statement.

In [ ]:
eglist = [10,50,30,12,6,8,100]

def egfunc(eglist):
    highest = max(eglist)
    lowest = min(eglist)
    first = eglist[0]
    last = eglist[-1]
    return highest,lowest,first,last
  
egfunc(eglist)

(100, 6, 10, 100)

In [ ]:
a,b,c,d = egfunc(eglist)
print (' a =',a,'\n b =',b,'\n c =',c,'\n d =',d)

 a = 100
 b = 6
 c = 10
 d = 100

### 4.3 Implicit arguments

When an argument of a function is common in majority of the cases or it is "implicit" this concept is used. For ex: below defined function **implicitadd( )** is a function accepts two arguments but most of the times the first argument needs to be added just by 3. Hence the second argument is assigned the value 3. Here the second argument is implicit.

Now if the second argument is not defined when calling the **implicitadd( )** function then it considered as 3. But if the second argument is specified then this value overrides the implicit value assigned to the argument

In [ ]:
def implicitadd(x,y=3):
    return x+y
  
print(implicitadd(4))
print(implicitadd(4,4))

7
8

### 4.4 Any number of arguments

If the number of arguments that is to be accepted by a function is not known then a asterisk symbol is used before the argument. The below function accepts any number of arguments, defines a list and appends all the arguments into that list and return the sum of all the arguments.

In [ ]:
def add_n(*args):
    res = 0
    reslist = []
    for i in args:
        reslist.append(i)
    print (reslist)
    return sum(reslist)

In [ ]:
add_n(1,2,3,4,5,6,7)

[1, 2, 3, 4, 5, 6, 7]

28

In [ ]:
add_n(1,2,3,4,5)

[1, 2, 3, 4, 5]

15

### 4.5 Some useful functions

#### 4.5.1 Lambda Functions

These are small functions which are not defined with any name and carry a single expression whose result is returned. Lambda functions comes very handy when operating with lists. These function are defined by the keyword lambda followed by the variables, a colon and the respective expression.

In [ ]:
z = lambda x: x * x
z(8)

64

#### 4.5.2 map Functions

map( ) function basically executes the function that is defined to each of the list's element separately. We can also add two lists. In addition with lambda function, other built in functions can also be used.

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9]
print(list(map(lambda x:x+2, list1)))

list2 = [9,8,7,6,5,4,3,2,1]
print(list(map(lambda x,y:x+y, list1,list2)))

[3, 4, 5, 6, 7, 8, 9, 10, 11]
[10, 10, 10, 10, 10, 10, 10, 10, 10]

#### 4.5.3 filter Functions

filter( ) function is used to filter out the values in a list. Note that filter() function returns the result in a new list.

In [ ]:
list1 = [1,2,3,4,5,6,7,8,9]
list(filter(lambda x:x<5,list1))

[1, 2, 3, 4]

## 5. Classes
Variables, Lists, Dictionaries etc in python is a object. Without getting into the theory part of Object Oriented Programming, explanation of the concepts will be done along this tutorial.

A class is declared as follows

---
class class_name:<br>

      Functions

---

In [ ]:
class FirstClass:
    pass

**pass** in python means do nothing.

Above, a class object named "FirstClass" is declared now consider a "egclass" which has all the characteristics of "FirstClass". So all you have to do is, equate the "egclass" to "FirstClass". In python jargon this is called as creating an instance. "egclass" is the instance of "FirstClass"

In [ ]:
egclass = FirstClass()
print(type(egclass))
print(type(FirstClass))

<class '__main__.FirstClass'>
<class 'type'>

Now let us add some "functionality" to the class. So that our "FirstClass" is defined in a better way. A function inside a class is called as a "Method" of that class

Most of the classes will have a function named "__init__". These are called as magic methods. In this method you basically initialize the variables of that class or any other initial algorithms which is applicable to all methods is specified in this method. A variable inside a class is called an attribute.

These helps simplify the process of initializing a instance. For example,

Without the use of magic method or __init__ which is otherwise called as constructors. One had to define a init( ) method and call the init( ) function.

But when the constructor is defined the __init__ is called thus intializing the instance created.

We will make our "FirstClass" to accept two variables name and symbol.

In [ ]:
class FirstClass:
    def __init__(self,name,symbol):
        self.name = name
        self.symbol = symbol

Now that we have defined a function and added the __init__ method. We can create a instance of FirstClass which now accepts two arguments.

In [ ]:
eg1 = FirstClass('one',1)
eg2 = FirstClass('two',2)

print (eg1.name, eg1.symbol)
print (eg2.name, eg2.symbol)

one 1
two 2

dir( ) function comes very handy in looking into what the class contains and what all method it offers. dir( ) of an instance also shows it's defined attributes.

In [ ]:
dir(FirstClass)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__']

In [ ]:
dir(eg1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'name',
 'symbol']

Changing the FirstClass function a bit,

In [ ]:
class FirstClass:
    def __init__(self,name,symbol):
        self.n = name
        self.s = symbol

In [ ]:
eg1 = FirstClass('one',1)
eg2 = FirstClass('two',2)

print (eg1.name, eg1.symbol)
print (eg2.name, eg2.symbol)

AttributeError: ignored

AttributeError, Remember variables are nothing but attributes inside a class? So this means we have not given the correct attribute for the instance.

In [ ]:
print (eg1.n, eg1.s)
print (eg2.n, eg2.s)

one 1
two 2

So now we have solved the error. Now let us compare the two examples that we saw.

When I declared self.name and self.symbol, there was no attribute error for eg1.name and eg1.symbol and when I declared self.n and self.s, there was no attribute error for eg1.n and eg1.s

From the above we can conclude that self is nothing but the instance itself.

Remember, self is not predefined it is userdefined. You can make use of anything you are comfortable with. But it has become a common practice to use self.

In [ ]:
class FirstClass:
    def __init__(asdf1234,name,symbol):
        asdf1234.n = name
        asdf1234.s = symbol

In [ ]:
eg1 = FirstClass('one',1)
eg2 = FirstClass('two',2)

print (eg1.n, eg1.s)
print (eg2.n, eg2.s)

one 1
two 2

Since eg1 and eg2 are instances of FirstClass it need not necessarily be limited to FirstClass itself. It might extend itself by declaring other attributes without having the attribute to be declared inside the FirstClass.

In [ ]:
eg1.cube = 1
eg2.cube = 8

dir(eg1)

['__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 'cube',
 'n',
 's']

Just like global and local variables as we saw earlier, even classes have it's own types of variables.

Class Attribute : attributes defined outside the method and is applicable to all the instances.

Instance Attribute : attributes defined inside a method and is applicable to only that method and is unique to each instance.

In [ ]:
class FirstClass:
    test = 'test'
    def __init__(self,name,symbol):
        self.name = name
        self.symbol = symbol

In [ ]:
eg3 = FirstClass('Three',3)
print (eg3.test, eg3.name)

test Three

Let us add some more methods to FirstClass.

In [ ]:
class FirstClass:
    def __init__(self,name,symbol):
        self.name = name
        self.symbol = symbol
    def square(self):
        return self.symbol * self.symbol
    def cube(self):
        return self.symbol * self.symbol * self.symbol
    def multiply(self, x):
        return self.symbol * x

In [ ]:
eg4 = FirstClass('Five',5)
print (eg4.square())
print (eg4.cube())
print (eg4.multiply(2))

25
125
10

### 5.1 Inheritance

There might be cases where a new class would have all the previous characteristics of an already defined class. So the new class can "inherit" the previous class and add it's own methods to it. This is called as inheritance.

Consider class SoftwareEngineer which has a method salary.

In [ ]:
class SoftwareEngineer:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def salary(self, value):
        self.money = value
        print (self.name,"earns",self.money)

In [ ]:
a = SoftwareEngineer('John',26)
a.salary(40000)

John earns 40000

Now consider another class Artist which tells us about the amount of money an artist earns and his artform.

In [ ]:
class Artist:
    def __init__(self,name,age):
        self.name = name
        self.age = age
    def money(self,value):
        self.money = value
        print (self.name,"earns",self.money)
    def artform(self, job):
        self.job = job
        print (self.name,"is a", self.job)

In [ ]:
b = Artist('Bob',20)
b.money(50000)
b.artform('Musician')

Bob earns 50000
Bob is a Musician

money method and salary method are the same. So we can generalize the method to salary and inherit the SoftwareEngineer class to Artist class. Now the artist class becomes,

In [ ]:
class Artist(SoftwareEngineer):
    def artform(self, job):
        self.job = job
        print (self.name,"is a", self.job)

In [ ]:
c = Artist('Henry',21)
c.salary(60000)
c.artform('Dancer')

Henry earns 60000
Henry is a Dancer

Suppose say while inheriting a particular method is not suitable for the new class. One can override this method by defining again that method with the same name inside the new class.

In [ ]:
class Artist(SoftwareEngineer):
    def artform(self, job):
        self.job = job
        print (self.name,"is a", self.job)
    def salary(self, value):
        self.money = value
        print (self.name,"earns",self.money)
        print ("I am overriding the SoftwareEngineer class's salary method")

In [ ]:
c = Artist('Henry',21)
c.salary(60000)
c.artform('Dancer')

Henry earns 60000
I am overriding the SoftwareEngineer class's salary method
Henry is a Dancer

### 5.2 Using List

In the below example, since xc.data is a list direct list operations can also be performed. Another use is that If the number of input arguments varies from instance to instance asterisk can be used as shown in second class example.

In [ ]:
class emptylist:
    def __init__(self):
        self.data = []
    def one(self,x):
        self.data.append(x)
    def two(self, x ):
        self.data.append(x**2)
    def three(self, x):
        self.data.append(x**3)

In [ ]:
xc = emptylist()
xc.one(1)
print (xc.data)

xc.data.append(8)
print (xc.data)

xc.two(3)
print (xc.data)

[1]
[1, 8]
[1, 8, 9]

In [ ]:
class NotSure:
    def __init__(self, *args):
        self.data = ''.join(list(args))

In [ ]:
yz = NotSure('I', 'Do' , 'Not', 'Know', 'What', 'To','Type')
yz.data

'IDoNotKnowWhatToType'

## Packages

### Installing packages

pip install [package] 

conda install [package]

In [ ]:
#!pip install numpy

### Importing packages

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

print(np.__version__)
print(pd.__version__)
print(tf.__version__)

1.18.5
1.1.4
2.3.0